---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
spec:
  type: NodePort
  selector:
    app: kafdrop
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30009
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafdrop-env-config
data:
  KAFKA_BROKERCONNECT: "kafka:9092"
  JMX_PORT: "8686"
  SERVER_PORT: "9000"
  CMD_ARGS: "--message.format=AVRO --schemaregistry.connect=http://localhost:8080"
  JVM_OPTS: "-Xmx2G -Xms1G"
  KAFKA_PROPERTIES_FILE: kafka.properties
  KAFKA_TRUSTSTORE_FILE: kafka.truststore.jks
  KAFKA_KEYSTORE_FILE: kafka.keystore.jks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      nodeSelector:
        servertype: vm
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:3.27.0
        envFrom:
        - configMapRef:
            name: kafdrop-env-config
        ports:
        - containerPort: 9000
          name: kafdrop-port
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Gi
            cpu: 4m
